WebShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebShop.Data;
using WebShop.Models;
using static System.Net.Mime.MediaTypeNames;

namespace WebShop.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ProductController : Controller
    {
        private readonly DbShop _context;

        public ProductController(DbShop context)
        {
            _context = context;
        }

        // GET: Product
        public async Task<IActionResult> Index()
        {
            var product = await (from ca in _context.ProductCategory
                           join p in _context.Product on ca.ProductId equals p.ProductId
                           join cc in _context.Category on ca.CategoryId equals cc.CategoryId
                           select ca).ToListAsync();

            var prCat = await _context.ProductCategory.Include(x => x.Product).Include(x => x.Category).ToListAsync();


            var dbShop = _context.Product.Include(p => p.MeasuringUnit);
            return View(await dbShop.ToListAsync());

            
        }

        // GET: Product/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .Include(p => p.MeasuringUnit)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Product/Create
        public IActionResult Create()
        {
            ViewData["MeasuringUnitId"] = new SelectList(_context.MeasuringUnit, "MeasuringUnitId", "Unit");
            return View(new Product());
        }

        // POST: Product/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid id, [Bind("ProductId,Name,CreatedDate,ModifiedDate,Quantity,Available,Price,Image,Description,MeasuringUnitId")]  Product product)
        {


            if (Request.Form.Files["Image"] != null)
            {
                IFormFile file = Request.Form.Files["Image"];
                var stream = file.OpenReadStream();
                BinaryReader br = new BinaryReader(stream);
                byte[] imgdata = br.ReadBytes((int)stream.Length);
              product.Image = imgdata;
            }  



            if (ModelState.IsValid)
            {
              
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MeasuringUnitId"] = new SelectList(_context.MeasuringUnit, "MeasuringUnitId", "Unit", product.MeasuringUnitId);
            return View(product);
        }


        // GET: Product/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["MeasuringUnitId"] = new SelectList(_context.MeasuringUnit, "MeasuringUnitId", "Unit", product.MeasuringUnitId);
            return View(product);
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ProductId,Name,CreatedDate,ModifiedDate,Quantity,Available,Price,Image,Description,MeasuringUnitId")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }


            if (Request.Form.Files["Image"] != null)
            {
                IFormFile file = Request.Form.Files["Image"];
                var stream = file.OpenReadStream();
                BinaryReader br = new BinaryReader(stream);
                byte[] imgdata = br.ReadBytes((int)stream.Length);
                product.Image = imgdata;
            }
            else
            {
                var image = _context.Product.AsNoTracking().FirstOrDefault(x => x.ProductId == product.ProductId).Image;
                product.Image = image;
                _context.Entry(product).State = EntityState.Detached;
            }


            if (ModelState.IsValid)
            {
                try
                {
                    _context.Entry(product).State = EntityState.Modified;
                   // _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MeasuringUnitId"] = new SelectList(_context.MeasuringUnit, "MeasuringUnitId", "Unit", product.MeasuringUnitId);
            return View(product);
        }

        // GET: Product/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .Include(p => p.MeasuringUnit)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            try
            {
                Product product = await _context.Product.FindAsync(id);
                if (product != null)
                {
                    List<ProductCategory> productCategories = await _context.ProductCategory.Where(x => x.ProductId == id).ToListAsync();
                    if (productCategories.Any())
                    {
                        _context.ProductCategory.RemoveRange(productCategories);
                        await _context.SaveChangesAsync();
                    }
                    List<OrderDetails> orderDetails = await _context.OrderDetail.Where(x => x.ProductId == id).ToListAsync();
                    if (orderDetails.Any())
                    {
                        _context.OrderDetail.RemoveRange(orderDetails);
                        await _context.SaveChangesAsync();
                    }

                }

                _context.Product.Remove(product);
                await _context.SaveChangesAsync();
               
            }
            catch(Exception ex)
            {
                TempData["Message"] = "Error: " + ex.Message;
            }
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(Guid id)
        {
            return _context.Product.Any(e => e.ProductId == id);
        }
    }
}

WebShop/Controllers/WebShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebShop.Common;
using WebShop.Data;
using WebShop.Models;

namespace WebShop.Controllers
{
    [AllowAnonymous]
    public class WebShopController : Controller
    {
        private readonly DbShop _context;

        public WebShopController(DbShop context)
        {
            _context = context;
        }

        // GET: WebShop
        public async Task<IActionResult> Index()
        {

            var productCategory = await _context.ProductCategory.Include(x => x.Product).Include(x => x.Category).ToListAsync();


          //  var dbShop = _context.Product.Include(p => p.MeasuringUnit);
            
            return View(productCategory);
        }

        [HttpGet]
        public ActionResult Review(ReviewContent review)
        {

            try
            {
                review.ReviewContentId = Guid.NewGuid();
                review.CreatedDate = DateTime.Today;

                _context.ReviewContent.Add(review);
                _context.SaveChanges();
                
            }
            catch(Exception ex)
            {
                throw ex;
            }

            return Json("ok");
        }


        [HttpGet()]
        [ActionName("Reviews")]
       
        public PartialViewResult Review(Guid productId)
        {
            if(productId == null)
            {
                Response.StatusCode = 405;
            }

            List<ReviewContent> reviews = _context.ReviewContent.Where(x => x.ProductId == productId).ToList();
            

            return PartialView("_Reviews", reviews);
        }


        public async Task<IActionResult> Product(int currentPage = 1)
        {
            //  var productCategory = await _context.ProductCategory.Include(x => x.Product).Include(x => x.Category).ToListAsync();
            ModelPaging productCategory = new ModelPaging(_context);
            productCategory.CurrentPage = currentPage;
            productCategory.Data = await _context.ProductCategory.Include(x => x.Product).Include(x => x.Category).Skip(currentPage - 1).Take(1).ToListAsync();

            //  var dbShop = _context.Product.Include(p => p.MeasuringUnit);

            return View(productCategory);
        }


        [HttpGet]
        public PartialViewResult TechSpec(Guid id)
        {
            if (id == null)
            {
                Response.StatusCode = 405;
            }


            string tehnSpec = " Technical Specification!!";
            return PartialView("_TechSpec", tehnSpec);

        }


        [HttpGet]
        public PartialViewResult Geometry(Guid? id)
        {
            if(id == null)
            {
                Response.StatusCode = 405;
            }


            string geo = "Not specifield yet!!";
            return PartialView("_Geometry", geo);
        }



        [HttpGet]
        public PartialViewResult Description(Guid? id)
        {
            string desc = string.Empty;
            try
            {
                desc =   _context.Product.FirstOrDefault(x => x.ProductId == id).Description;
            }
            catch (Exception ex)
            {
                desc =ex.Message;
            }
            return  PartialView("_Description", desc);
        }


        // GET: WebShop/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product prod = await _context.Product.Include(x => x.MeasuringUnit).FirstOrDefaultAsync(x => x.ProductId == id);
             
            
            
            ProductCategory product = await _context.ProductCategory.Include(x => x.Product).Include(x => x.Category).FirstOrDefaultAsync(x => x.Product.ProductId == id);
            product.Product = prod;
            product.ProductId = prod.ProductId;


            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: WebShop/Create
        public IActionResult Create()
        {
            ViewData["MeasuringUnitId"] = new SelectList(_context.MeasuringUnit, "MeasuringUnitId", "Name");
            return View();
        }

        // POST: WebShop/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,Name,CreatedDate,ModifiedDate,Quantity,Available,Price,Image,MeasuringUnitId")] Product product)
        {
            if (ModelState.IsValid)
            {
                product.ProductId = Guid.NewGuid();
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MeasuringUnitId"] = new SelectList(_context.MeasuringUnit, "MeasuringUnitId", "Name", product.MeasuringUnitId);
            return View(product);
        }

        // GET: WebShop/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["MeasuringUnitId"] = new SelectList(_context.MeasuringUnit, "MeasuringUnitId", "Name", product.MeasuringUnitId);
            return View(product);
        }

        // POST: WebShop/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ProductId,Name,CreatedDate,ModifiedDate,Quantity,Available,Price,Image,MeasuringUnitId")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MeasuringUnitId"] = new SelectList(_context.MeasuringUnit, "MeasuringUnitId", "Name", product.MeasuringUnitId);
            return View(product);
        }

        // GET: WebShop/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .Include(p => p.MeasuringUnit)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: WebShop/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(Guid id)
        {
            return _context.Product.Any(e => e.ProductId == id);
        }
    }
}

WebShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!--Paypal-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    <title>@ViewData["Title"] - WebShop</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" id="navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebShop</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>



                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="Product" asp-action="Index">Product</a></li>
                        <li><a asp-area="" asp-controller="MeasuringUnit" asp-action="Index">Unit of measure</a></li>
                        <li><a asp-area="" asp-controller="Category" asp-action="Index">Category</a></li>
                        <li><a asp-area="" asp-controller="ProductCategory" asp-action="Index">ProductCategory</a></li>
                        <li><a asp-area="" asp-controller="Admin" asp-action="Index">Admin</a></li>

                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Home" asp-action="Gallery">Gallery</a></li>
                        <li class="dropdown">
                            <a class="dropbtn">WebShop</a>
                            <ul class="dropdown-content" aria-labelledby="dropdownMenuLink">
                                <li class="dropdown-item">
                                    <a asp-area="" asp-controller="WebShop" asp-action="Index">Shopping</a>
                                </li>
                                <li class="dropdown-item">
                                    <a asp-area="" asp-controller="WebShop" asp-action="Product">Product</a>
                                </li>
                            </ul>
                        </li>

                        <li class="active">
                            <a href="@Url.Action("Index", "Cart")">
                                <span class="glyphicon glyphicon-shopping-cart" style="color:green"></span>Cart <span class="badge">@HttpContextAccessor.HttpContext.Session.GetInt32("count")</span>
                            </a>
                        </li>
                    }

                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container">

        @RenderBody()
       
    </div>
   
        <hr />
      
  
    <footer>

        <div class="row align-items-center">

            <div class="col-lg-4">
                <p>Join us on</p>

                <p> <a style="color:whitesmoke" href="#"> <i class="fa fa-facebook-square  fa-2x"></i>Facebook</a> </p>

               <p>  <a style="color:whitesmoke" href="#"><i class="fa fa-twitter fa-2x"></i>Twitter</a> </p>

               <p>  <a style="color:whitesmoke" href="#"><i class="fa fa-instagram fa-2x"></i>Instagram</a> </p>

            </div>

            <div class="col-lg-4">
   
             <p>&copy; @DateTime.Now.Year - WebShop</p>

            </div>

            <div class="col-lg-4">

                <ul class="list-unstyled mb-0">
                    <li>
                        <i class="glyphicon glyphicon-map-marker"></i>
                        <p>San Francisco, CA 94126, USA</p>
                    </li>

                    <li>
                        <i class="glyphicon glyphicon-phone-alt"></i>
                        <p>+ 01 234 567 89</p>
                    </li>

                    <li>
                        <i class="glyphicon glyphicon-envelope"></i>
                        <p>contact@easybuy.com</p>
                    </li>
                </ul>

            </div>

        </div>
    </footer>
               

   


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>


     <!--   <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script> -->


        <link type="text/css" rel="stylesheet" href="~/css/magiczoomplus.css" />
        <script type="text/javascript" src="~/js/magiczoomplus.js"></script>


        <!--Import jQuery before export.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>


        <!--Data Table-->
        <script type="text/javascript" src=" https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src=" https://cdn.datatables.net/buttons/1.2.4/js/dataTables.buttons.min.js"></script>


        <!--Export table buttons-->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
        <script type="text/javascript" src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.24/build/pdfmake.min.js"></script>
        <script type="text/javascript" src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.24/build/vfs_fonts.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.html5.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.2.1/js/buttons.print.min.js"></script>

        <!--Export table button CSS-->

        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.4/css/buttons.dataTables.min.css">





        
        <!-- BS JavaScript -->
        <script type="text/javascript" src="~/js/bootstrap.min.js"></script>



        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
    
</body>
</html>